X-Ray:
  Display Name: "&cX-Ray"
  Lore:
    - "&7Place any information in here!"
    - "&7Supports multi-line"
  Tier 1:
    Display Name: "&61 Day Ban"
    Lore:
      - "&7Ban the player for 1 Day"
      - "&7for x-ray"
    Player Commands:
      - "tempban %player% 1d X-Ray -s"
    Console Commands:
      - "say Configure GUIConfig.yml"
  Tier 2:
    Display Name: "&67 Day Ban"
    Lore:
      - "&7Ban the player for 7 Days"
      - "&7for x-ray"
    Player Commands:
      - "tempban %player% 7d X-Ray -s"
  Tier 3:
    Display Name: "&615 Day Ban"
    Lore:
      - "&7Ban the player for 15 Days"
      - "&7for x-ray"
    Player Commands:
      - "tempban %player% 15d X-Ray -s"
  Tier 4:
    Display Name: "&630 Day Ban"
    Lore:
      - "&7Ban the player for 30 Days"
      - "&7for x-ray"
    Player Commands:
      - "tempban %player% 30d X-Ray -s"
Flying:
  Display Name: "&cFlying"
  Lore:
    - "&7Place any information in here!"
    - "&7Supports multi-line"
  Tier 1:
    Display Name: "&615 Day Ban"
    Lore:
      - "&7Ban the player for 5 Days"
      - "&7for flying"
    Player Commands:
      - "tempban %player% 15d Flying -s"
    Console Commands:
      - "say Configure GUIConfig.yml"
  Tier 2:
    Display Name: "&630 Day Ban"
    Lore:
      - "&7Ban the player for 5 Days"
      - "&7for flying"
    Player Commands:
      - "tempban %player% 30d Flying -s"
  Tier 3:
    Display Name: "&660 Day Ban"
    Lore:
      - "&7Ban the player for 5 Days"
      - "&7for flying"
    Player Commands:
      - "tempban %player% 60d Flying -s"
  Tier 4:
    Display Name: "&4Permanent Ban"
    Lore:
      - "&7Ban the player permanently"
      - "&7for flying"
    Player Commands:
      - "ban %player% Flying -s"